require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/save_states", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # SaveState. As you add validations to SaveState, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SaveState.create! valid_attributes
      get save_states_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      save_state = SaveState.create! valid_attributes
      get save_state_url(save_state)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_save_state_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      save_state = SaveState.create! valid_attributes
      get edit_save_state_url(save_state)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SaveState" do
        expect {
          post save_states_url, params: { save_state: valid_attributes }
        }.to change(SaveState, :count).by(1)
      end

      it "redirects to the created save_state" do
        post save_states_url, params: { save_state: valid_attributes }
        expect(response).to redirect_to(save_state_url(SaveState.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SaveState" do
        expect {
          post save_states_url, params: { save_state: invalid_attributes }
        }.to change(SaveState, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post save_states_url, params: { save_state: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested save_state" do
        save_state = SaveState.create! valid_attributes
        patch save_state_url(save_state), params: { save_state: new_attributes }
        save_state.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the save_state" do
        save_state = SaveState.create! valid_attributes
        patch save_state_url(save_state), params: { save_state: new_attributes }
        save_state.reload
        expect(response).to redirect_to(save_state_url(save_state))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        save_state = SaveState.create! valid_attributes
        patch save_state_url(save_state), params: { save_state: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested save_state" do
      save_state = SaveState.create! valid_attributes
      expect {
        delete save_state_url(save_state)
      }.to change(SaveState, :count).by(-1)
    end

    it "redirects to the save_states list" do
      save_state = SaveState.create! valid_attributes
      delete save_state_url(save_state)
      expect(response).to redirect_to(save_states_url)
    end
  end
end
